http_port 3128
pinger_enable off
acl allowed_registry dstdomain registry.npmjs.org
acl allowed_ssl_ports port 443
acl CONNECT method CONNECT
http_access deny !allowed_ssl_ports
http_access allow CONNECT allowed_registry
http_access allow allowed_registry
http_access deny all
cache deny all
via off
forwarded_for delete
request_header_access X-Forwarded-For deny all
request_header_access Via deny all
