import { Link, useLocation } from "wouter";
import developerPhoto from "@/assets/saqlain-developer.jpg";

type InformationKind = "guide" | "privacy" | "terms";
type FaqItem = { question: string; answer: string };
type Section = { title: string; paragraphs: string[]; checklist?: string[]; faq?: FaqItem[] };
type SummaryRow = { topic: string; guidance: string };
type InformationContent = { title: string; eyebrow: string; intro: string; summary: SummaryRow[]; sections: Section[] };

const pageContent: Record<InformationKind, InformationContent> = {
    guide: {
        title: "SK Coder User Manual",
        eyebrow: "SK Coder",
        intro: "SK Coder keeps everyday coding work in one workspace: files, editor, previews, results, package tools, and reviewed AI help. This manual explains how to work confidently, protect important projects, and understand the availability of each tool.",
        summary: [
            { topic: "Start with Files", guidance: "Create, import, organize, rename, move, copy, export, or remove files and folders from the workspace." },
            { topic: "Open the right view", guidance: "Readable text opens in Editor. Media and browser-friendly documents can open in Preview. Supported source files may offer Run or Result Center." },
            { topic: "Use SK Shell for projects", guidance: "A connected workspace terminal is the right place for project folders, package scripts, build commands, repeated input, and development-server work." },
            { topic: "Keep work available", guidance: "Browser storage keeps a local project copy. When a workspace service is available, the project can also be kept in a private working space for terminal, runner, preview, and package tasks." },
            { topic: "Keep your own backup", guidance: "Export important projects before clearing browser data, changing devices, or replacing a workspace." },
            { topic: "Review assisted work", guidance: "AI can explain, draft, and propose a scoped action. You remain in control of whether a file or command action is approved." },
        ],
        sections: [
            { title: "Working with files without losing your place", paragraphs: ["Files is the starting point for a project. You can bring in individual files, folders, and compatible archives, then continue opening tabs, switching panels, or checking a preview while an operation is in progress. SK Coder keeps completed work visible instead of replacing the workspace with a blank loading view.", "A file type helps SK Coder choose a useful action, but the content of the file still matters. A readable text file can be edited. A binary, compiled, encrypted, or otherwise non-text file is kept intact and is not misrepresented as source code."], checklist: ["Use Import for files, folders, and compatible archives.", "Use Export to download a selected item or the current project as an archive.", "Use Preview for HTML, Markdown, images, SVG, audio, video, PDFs, and similar browser-readable files.", "Use Editor for genuinely readable text, including configuration and source files."] },
            { title: "Imports, exports, archives, and larger projects", paragraphs: ["A project import is not only a single instant action. The browser must inspect file data, create workspace entries, and safely store the result. SK Coder therefore reports meaningful stages and percentage feedback for multi-file work, while keeping the interface usable as the import continues.", "Compatible ZIP-family archives may be extracted into a project folder when their structure is readable. The original archive should not be treated as source code. If an archive cannot be safely opened in the browser, it remains a file that you can preserve or download rather than a broken imitation of an extracted project."], checklist: ["Do not close the browser tab while an import or export is active.", "Archive families include ZIP, JAR, AAR, WAR, EAR, APK, XAPK, and APKS.", "Large media and binary files are retained as file data when possible instead of being expanded into unreliable text."] },
            { title: "Editor, previews, results, and SK Shell", paragraphs: ["SK Coder recognizes a broad range of readable source, markup, configuration, data, build, and project files. This includes JavaScript, TypeScript, Python, Java, Kotlin, C, C++, Rust, Go, C#, F#, PHP, Ruby, Bash, PowerShell, HTML, CSS, JSON, XML, YAML, TOML, SQL, Dart, Lua, R, Swift, Scala, Haskell, Perl, Elixir, Erlang, OCaml, Fortran, COBOL, assembly, and related project metadata. Recognition chooses a useful editor, preview, result view, or terminal entry point; it does not falsely mean every runtime, framework, mobile target, engine, codec, or licensed platform is installed.", "SK Shell is a real interactive terminal when the private workspace connection is available. Commands and project runs are executed in that workspace rather than being displayed as made-up output. It can temporarily restore a dropped connection and return to the same private project. A connection notice means the terminal is waiting for a real connection; it never means a command has run when it has not."], checklist: ["Browser previews are suited to HTML, CSS, JavaScript, Markdown, SVG, images, audio, video, PDFs, and local browser-readable assets.", "Node projects commonly use package.json and npm-style scripts; Python projects commonly use requirements.txt or pyproject.toml; Java and Kotlin projects commonly use source files or Gradle/Maven configuration; C and C++ projects commonly use a Makefile or CMakeLists.txt; Rust uses Cargo.toml; Go uses go.mod; .NET projects use a project file or solution.", "A language can be recognized even when its compiler or runtime is not active in the current workspace. In that case, SK Coder shows an unavailable or failed condition rather than inventing output.", "Run with Display is for compatible graphical examples that can be presented in Preview. It is not a mobile emulator or a substitute for a full desktop game-development setup."] },
            { title: "Workspace storage and availability", paragraphs: ["Your browser keeps a local project copy using the storage available on your device. When workspace service capacity is available, SK Coder can keep a private working copy for terminal commands, native runs, packages, supported previews, and compatible package tasks. Each private workspace is separate from other users and is not shared through the file explorer, terminal history, or runtime session.", "A normal working copy is retained for up to 72 hours. If you choose Delete server copy, it enters a four-hour Undo period before removal. The local browser project remains available after a server copy is deleted. When service capacity is busy or a connection is temporarily unavailable, editing, imports, exports, and browser-friendly previews remain available from the local project copy."], checklist: ["Use Settings → Workspace to review the server-copy status, schedule a delete, or undo a scheduled delete.", "Export important work before changing devices, clearing site data, or making a major package change.", "A browser-stored project can continue editing when a workspace connection is unavailable, but server-required tools become available only after a private workspace is connected."] },
            { title: "AI Assistant, AI keys, and reviewed terminal actions", paragraphs: ["The assistant can explain selected code, work from a file or folder context you deliberately attach, and prepare a proposed action such as opening a file, drafting a change, creating a folder, renaming an item, opening Preview, running supported code, or proposing a terminal command. AI does not receive the authority to operate a project silently: file changes and terminal commands remain visible for review before they are applied.", "Provider connections are configured in Settings. You can paste an API key, choose or search a model, add a documented custom model ID, and use a compatible HTTPS endpoint only when the provider documents that API shape. SK Coder can test the connection and report the provider response, such as an invalid key, missing model permission, credit limit, rate limit, or unreachable service. A key is not included in a project export or connector export."], checklist: ["Use Allow once only after checking the exact file, path, command, and proposed change.", "A terminal proposal is limited to the active workspace command scope; it is not permission to access host secrets, unrelated workspaces, Docker, or deployment controls.", "Use Deny to reject a proposed action without changing your workspace.", "Keep passwords, private keys, environment files, access tokens, and confidential data out of prompts and attachments."] },
            { title: "GitHub connections and project privacy", paragraphs: ["GitHub is optional. When you choose to connect it, use a fine-grained personal access token, restrict it to the repositories you intend to use, and grant only the Contents permission needed for the action. Read access is enough for importing. Write access should be granted only when you choose to push changes. Codespaces permission is separate and should be added only if you use Codespaces features.", "The GitHub token is held in the local browser workspace state and is used when you deliberately choose a GitHub action. Disconnect removes the saved token from that browser workspace. Do not paste a token into source files, the terminal, chat prompts, bug reports, screenshots, or a public repository. Revoke and replace any token that you believe has been exposed."], },
            { title: "Packages, images, and repackaging", paragraphs: ["Package tools can browse ZIP-family package contents, open a genuinely readable entry, replace selected files and image resources, retain a local draft, and export a repackaged archive. When a readable manifest and launcher resource are available, the package view can surface useful details and the current launcher image for replacement.", "An exported package is not automatically a verified installable mobile application. Editing a signed Android package can invalidate its original signature. Compiled manifests and resources need a compatible decode workflow before they can be read or changed safely, and distribution still requires authorization, signing, and verification by the rightful owner."], checklist: ["Use Repackage to review the package and prepare a local archive export.", "Only edit packages and content that you are authorized to use.", "Keep an original package copy before replacing a resource or text entry."] },
            { title: "Saving work responsibly", paragraphs: ["The workspace uses browser-held storage where available. That makes it possible to continue with files and local package drafts in the same browser, but browser storage is not a replacement for a backup strategy. Clearing site data, using a different browser profile, or switching devices can remove locally held workspace data.", "A good habit is simple: export before major changes, retain the original for package work, and keep private credentials out of project files and screenshots. SK Coder preserves a file and reports an unavailable tool or an error when a required capability is not currently available."], },
            { title: "Frequently asked questions", paragraphs: ["SK Coder is built to make everyday development work simpler: open a project, understand its files, write code, check a preview, use the tools that fit the project, and keep control of every important action."], faq: [
                { question: "What is SK Coder for?", answer: "SK Coder is a practical coding workspace for learners, creators, and developers. It brings files, code editing, previews, supported project tools, package work, and reviewed AI assistance together so you can focus on the work instead of moving between many small tools." },
                { question: "Who can use SK Coder?", answer: "It is useful for people learning to code, building personal projects, reviewing files, experimenting with web pages, working with source archives, and developing supported software projects. You can begin with a simple file and grow into a folder-based project when you are ready." },
                { question: "Is SK Shell a real terminal?", answer: "Yes. When your private workspace is connected, SK Shell sends your command to that workspace and shows the real result. It does not invent output. If the connection is restoring, the terminal shows a clear notice and waits until it can reconnect." },
                { question: "Why does the terminal sometimes reconnect?", answer: "A live connection can pause when a phone changes network, a browser is put in the background, or a service is briefly restarting. SK Coder keeps the workspace identity and tries to restore the connection safely. It never reruns a command automatically when the previous result is uncertain." },
                { question: "How long is my workspace kept?", answer: "A connected server workspace is normally kept for up to 72 hours. If you choose Delete server copy, it stays available for Undo for four hours before removal. Your browser project remains available separately, and exporting important work is still a good habit." },
                { question: "Can I keep working if a workspace connection is unavailable?", answer: "Yes. You can continue editing files, importing and exporting work, and using compatible browser previews from the project stored in your browser. Actions that need a connected workspace, such as interactive terminal commands, native project builds, supported package installs, graphical displays, and package rebuilding, become available again when the workspace reconnects." },
                { question: "Which programming languages and projects can I work with?", answer: "SK Coder can recognize a wide range of source and project files. Active runtime profiles cover common work with Node.js and TypeScript, Python, Java and Kotlin, C and C++, Rust, Go, .NET and C#, PHP, Ruby, and Bash. A project may still need its own files, dependencies, entry point, and build settings before it can run." },
                { question: "Can I import ZIP files, APK files, and project folders?", answer: "Yes. SK Coder can import files, folders, and compatible archives. Readable source can be opened for editing, while binary content is kept as file data for safe preview, replacement, package work, or export. Always keep an original copy of an important package before editing it." },
                { question: "Are my files and terminal history shared with other users?", answer: "No. Each workspace has its own private access credentials, files, runtime activity, and terminal history. Do not share API keys, private links, access tokens, browser profiles, or private project exports with anyone else." },
                { question: "How does AI assistance work?", answer: "The assistant can help explain code, draft changes, and suggest a scoped next action. You review proposed file changes and terminal commands before allowing them. Use AI as a helpful collaborator, and keep private credentials and sensitive information out of prompts and attachments." },
                { question: "Why choose SK Coder?", answer: "SK Coder is designed by Saqlain King for people who want a focused, approachable workspace that respects their files and decisions. It aims to make useful coding tools easier to reach without replacing the developer’s judgment or hiding important actions." },
            ] },
        ],
    },
    privacy: {
        title: "Privacy Policy",
        eyebrow: "SK Coder",
        intro: "This policy explains the practical choices involved when you use SK Coder: where files can be held, when information leaves the browser, and what you should consider before connecting an external service.",
        summary: [
            { topic: "Workspace files", guidance: "Files and package drafts are held in browser storage where possible. When workspace tools are used, a private working copy may also be used for that session." },
            { topic: "AI context", guidance: "A request can include your prompt and the workspace items you intentionally select. Providers apply their own terms to their service." },
            { topic: "Connected services", guidance: "GitHub, AI providers, package registries, hosting services, and similar connections are separate services with their own policies and controls." },
            { topic: "Your control", guidance: "You can export a project, dismiss a notice, remove local work, decline an AI action, or avoid connecting a service." },
        ],
        sections: [
            { title: "Files and local browser storage", paragraphs: ["Files you create or import can be held in browser storage in order to reopen the workspace in the same browser. Large media, archives, and package drafts may remain as their original file data so they can be previewed, replaced, or exported without turning them into long text strings.", "You remain responsible for retaining a backup of important work. Clearing browser site data can remove locally held files, settings, package drafts, and workspace details. Export work you want to keep before clearing site data, changing browser profiles, or moving to another device."] },
            { title: "Runs, previews, package work, and downloads", paragraphs: ["When you choose a run, terminal, build, or display action that needs a compatible workspace service, the files required for that action may be used in a private working copy. Normal workspace retention is up to 72 hours. If you choose to delete the server copy, it enters a four-hour undo period before removal. Treat any run or preview as an operational session, not as your only copy of a project.", "Exporting a project or repackaging an archive creates a browser download. A local package draft reflects selected changes such as a replaced readable entry or image resource. Only work with packages that you are permitted to access, modify, and distribute."] },
            { title: "AI requests, API keys, and provider connections", paragraphs: ["An AI request sends the message you write and the workspace context you intentionally select to the provider you configure. Sensitive material such as private keys, credentials, environment files, and personal access tokens should not be shared as routine context. The provider may handle submitted information under its own privacy policy, retention practice, pricing, and regional rules.", "An API key is used to request the provider service you select. It is not included when you export a project or connector configuration. Choose a provider you trust with the code or content you send, and remove a key from Settings when you no longer need it. If a key may have been exposed, revoke it with the provider and create a replacement instead of simply hiding it in the interface."], checklist: ["Review an attachment before sending it.", "Use the smallest useful GitHub permission set.", "Keep credentials out of source code, screenshots, public repositories, feedback reports, and AI prompts."] },
            { title: "GitHub tokens and repository access", paragraphs: ["A GitHub connection uses the token and repository permissions that you choose. Select only the repositories required for your work and use a fine-grained token where possible. Read permission is appropriate for importing; write permission should be reserved for a deliberate push. The token is used when you choose a GitHub action and can be removed with Disconnect in Settings.", "Repository contents, commit history, and file names can contain sensitive information. Review the repository and branch before importing or pushing. Never put a token in a project file, README, screenshot, feedback report, or AI message. Revoke the token from GitHub immediately if it may have been revealed."], },
            { title: "Notices, feedback, and your choices", paragraphs: ["Notifications explain activity such as an import, export, package action, or error. They can be closed when you no longer need them. The feedback form prepares a message in your email application; it does not silently submit a report in the background.", "You can decide whether to import data, connect a service, approve an action, run a command, create a download, or remove locally held information. Questions and reports can be sent through the Feedback page with the details needed to understand the issue."] },
        ],
    },
    terms: {
        title: "Terms and Conditions",
        eyebrow: "SK Coder",
        intro: "These terms set clear expectations for using SK Coder, its workspace tools, optional runtime actions, package features, and external connections. They are written to make practical boundaries understandable before they become a surprise.",
        summary: [
            { topic: "Authorized work", guidance: "Use code, repositories, media, packages, accounts, and services only when you have the right to use them." },
            { topic: "Honest runtime limits", guidance: "A file extension alone cannot guarantee that a project, package, engine, codec, or platform target can run in the available environment." },
            { topic: "Connected accounts", guidance: "Third-party services retain their own terms, pricing, reliability, and privacy requirements." },
            { topic: "Independent backups", guidance: "Keep a separate copy of important work before major edits, browser-data cleanup, or package changes." },
        ],
        sections: [
            { title: "Your content and approvals", paragraphs: ["Use SK Coder only with materials, repositories, accounts, media, package files, and services that you are allowed to access and use. You are responsible for commands, dependencies, downloads, builds, external-service operations, and AI proposals that you approve.", "Review a proposed file action or terminal command before approving it. A reviewed action is designed to make the intended scope visible; it does not transfer ownership, licensing rights, or responsibility for the result."], },
            { title: "Runtime and display boundaries", paragraphs: ["SK Coder provides practical actions according to the selected file and the active workspace. It does not guarantee that every extension, programming language, dependency, operating-system target, database, browser engine, game engine, native application, codec, or licensed tool can be built or run in every session.", "Browser-held projects remain useful for editing, imports, exports, and compatible local previews during a temporary workspace interruption. Interactive terminal commands, native builds, package installation, graphical display, and package rebuilding require a compatible private workspace to be connected. Graphical display is intended for compatible functional examples and is not a promise of mobile emulation, hardware-accelerated graphics, desktop performance, or high-speed online gameplay."] },
            { title: "Security and external services", paragraphs: ["Protect API keys, GitHub tokens, private source files, package files, and downloaded archives. Grant only the permissions that a task needs, and remove or rotate credentials if you believe they have been exposed. Keep your browser, device, accounts, and recovery methods protected with the security controls offered by each service.", "AI providers, GitHub, package registries, hosting companies, and other external services operate under their own acceptable-use rules, privacy policies, availability conditions, and prices. No browser application can promise that every future attack, unsafe dependency, compromised device, or third-party outage is impossible. Review connected services carefully and follow their terms before using them."] },
            { title: "Feedback and problem reports", paragraphs: ["If a feature does not work as expected, preserve the file type, the action you chose, the error shown, and the steps needed to repeat the issue. Those details make it possible to investigate without guessing.", "The Feedback page creates an addressed message in your email application. You remain in control of the message and choose whether to send it. Do not include passwords, tokens, private keys, or confidential information in a report."] },
        ],
    },
};

const navItems: Array<{ kind: InformationKind; label: string }> = [
    { kind: "guide", label: "User Manual" },
    { kind: "privacy", label: "Privacy" },
    { kind: "terms", label: "Terms" },
];

export default function InformationPage({ kind }: { kind: InformationKind }) {
    const [location] = useLocation();
    const content = pageContent[kind];
    return <main style={{ minHeight: "100vh", background: "radial-gradient(circle at 88% 0%, rgba(88,166,255,0.15), transparent 29%), radial-gradient(circle at 0% 32%, rgba(56,139,253,0.08), transparent 25%), #0d1117", color: "#e6edf3", fontFamily: "var(--font-ui)", padding: "clamp(1rem, 4vw, 3rem)" }}>
      <div style={{ width: "min(1020px, 100%)", margin: "0 auto" }}>
        <header style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: "1rem", flexWrap: "wrap", paddingBottom: "1.1rem", borderBottom: "1px solid #30363d" }}>
          <Link href="/" style={{ display: "inline-flex", alignItems: "center", gap: 8, color: "#f0f6fc", textDecoration: "none", fontWeight: 800, letterSpacing: "-0.02em" }}><span style={{ display: "grid", placeItems: "center", width: 28, height: 28, borderRadius: 8, background: "#58a6ff", color: "#0d1117", fontSize: 12 }}>SK</span> SK Coder</Link>
          <nav style={{ display: "flex", gap: "0.4rem", flexWrap: "wrap" }} aria-label="Information pages">
            {navItems.map((item) => <Link key={item.kind} href={`/${item.kind}`} style={{ padding: "0.44rem 0.62rem", borderRadius: 7, color: location === `/${item.kind}` ? "#0d1117" : "#c9d1d9", background: location === `/${item.kind}` ? "#58a6ff" : "rgba(33,38,45,0.86)", border: location === `/${item.kind}` ? "1px solid #58a6ff" : "1px solid #30363d", textDecoration: "none", fontSize: 12, fontWeight: 750 }}>{item.label}</Link>)}
          </nav>
        </header>
        <section style={{ padding: "clamp(2.2rem, 7vw, 5.4rem) 0 2rem" }}>
          <p style={{ color: "#58a6ff", fontSize: 12, fontWeight: 800, letterSpacing: "0.12em", textTransform: "uppercase", margin: 0 }}>{content.eyebrow}</p>
          <h1 style={{ maxWidth: 800, fontSize: "clamp(2.15rem, 6vw, 4.1rem)", letterSpacing: "-0.055em", lineHeight: 1.02, margin: "0.75rem 0 1rem" }}>{content.title}</h1>
          <p style={{ maxWidth: 790, color: "#b7c0cb", fontSize: "clamp(1rem, 2vw, 1.17rem)", lineHeight: 1.78, margin: 0 }}>{content.intro}</p>
        </section>
        <section aria-label="Quick reference" style={{ overflow: "hidden", border: "1px solid #30363d", borderRadius: 14, background: "rgba(22,27,34,0.86)", marginBottom: "1.6rem" }}>
          <div style={{ padding: "1rem 1.1rem", borderBottom: "1px solid #30363d" }}><h2 style={{ margin: 0, fontSize: 16 }}>At a glance</h2></div>
          <div style={{ overflowX: "auto" }}><table style={{ width: "100%", borderCollapse: "collapse", minWidth: 580, color: "#c9d1d9", fontSize: 13 }}><thead><tr style={{ textAlign: "left", color: "#8b949e", fontSize: 11, letterSpacing: "0.08em", textTransform: "uppercase" }}><th style={{ padding: "0.8rem 1.1rem", width: "29%" }}>Topic</th><th style={{ padding: "0.8rem 1.1rem" }}>What it means in practice</th></tr></thead><tbody>{content.summary.map((row, index) => <tr key={row.topic} style={{ borderTop: "1px solid #30363d", background: index % 2 ? "rgba(13,17,23,0.48)" : "transparent" }}><th scope="row" style={{ padding: "0.9rem 1.1rem", textAlign: "left", color: "#f0f6fc", verticalAlign: "top" }}>{row.topic}</th><td style={{ padding: "0.9rem 1.1rem", lineHeight: 1.6 }}>{row.guidance}</td></tr>)}</tbody></table></div>
        </section>
        <section style={{ display: "grid", gap: "1rem", paddingBottom: "2rem" }}>
          {content.sections.map((section, index) => <article key={section.title} style={{ padding: "clamp(1.1rem, 3vw, 1.55rem)", border: "1px solid #30363d", background: index % 2 ? "rgba(22,27,34,0.92)" : "rgba(13,17,23,0.82)", borderRadius: 14, boxShadow: index === 0 ? "0 18px 45px rgba(0,0,0,0.12)" : "none" }}><h2 style={{ margin: "0 0 0.65rem", fontSize: "clamp(1.1rem, 2vw, 1.3rem)", letterSpacing: "-0.015em" }}>{section.title}</h2>{section.paragraphs.map((paragraph) => <p key={paragraph} style={{ maxWidth: 860, margin: "0.6rem 0", color: "#c9d1d9", lineHeight: 1.78, fontSize: 14 }}>{paragraph}</p>)}{section.faq?.length ? <div style={{ display: "grid", gap: "0.8rem", marginTop: "1rem" }}>{section.faq.map((item) => <div key={item.question} style={{ border: "1px solid rgba(88,166,255,0.28)", background: "rgba(56,139,253,0.07)", borderRadius: 10, overflow: "hidden" }}><h3 style={{ margin: 0, padding: "0.72rem 0.85rem", color: "#f0f6fc", background: "rgba(88,166,255,0.14)", fontSize: "clamp(0.95rem, 1.7vw, 1.04rem)", lineHeight: 1.4 }}>{item.question}</h3><p style={{ maxWidth: 860, margin: 0, padding: "0.78rem 0.85rem 0.88rem", color: "#c9d1d9", lineHeight: 1.75, fontSize: 14 }}>{item.answer}</p></div>)}</div> : null}{section.checklist?.length ? <div style={{ display: "grid", gap: "0.5rem", marginTop: "0.9rem", paddingTop: "0.85rem", borderTop: "1px solid #30363d" }}>{section.checklist.map((item) => <div key={item} style={{ display: "grid", gridTemplateColumns: "16px 1fr", gap: "0.55rem", color: "#b7c0cb", lineHeight: 1.58, fontSize: 13 }}><span aria-hidden="true" style={{ color: "#58a6ff", fontWeight: 900 }}>✓</span><span>{item}</span></div>)}</div> : null}</article>)}
        </section>
        <footer style={{ display: "flex", alignItems: "center", gap: "0.85rem", padding: "1.3rem 0 0.8rem", borderTop: "1px solid #30363d", color: "#8b949e" }}><img src={developerPhoto} alt="Saqlain King" style={{ flex: "0 0 auto", width: 42, height: 42, borderRadius: "50%", objectFit: "cover", border: "1px solid #58a6ff" }}/><div><strong style={{ display: "block", color: "#c9d1d9", fontSize: 13 }}>Saqlain King</strong><span style={{ fontSize: 12 }}>Developed by Saqlain King</span></div></footer>
      </div>
    </main>;
}
